website/auth.py
from flask import Blueprint, render_template, redirect, flash, url_for, request
from flask_login import login_user, current_user, login_required, logout_user
from flask_mail import Message, Mail
from werkzeug.security import generate_password_hash, check_password_hash

import main
from website import db
from website.forms import RegistrationForm, LoginForm, ResetPasswordForm, RequestResetForm
from website.models import User
auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('views.home'))
            flash(f'Welcome {form.email.data}!', category='success')
            return redirect(url_for('views.home'))
        else:
            flash('Login unsuccessful, please check email or password', category='error')
            return redirect(url_for('auth.login'))
    return render_template('login.html', title='Login', form=form)


@auth.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data,
                    password=generate_password_hash(form.password.data, method='sha256'))
        db.session.add(user)
        db.session.commit()
        login_user(user)
        flash(f'Account created for {form.username.data}!', category='success')
        return redirect(url_for('auth.login'))
    return render_template('register.html', title='Register', form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.index'))


def send_reset_email(user,mail=Mail):
    mail.init_app(main.app)

    token = user.get_reset_token(user)
    msg = Message('Password Reset Request', sender='noreply@demo.com', recipients=[user.email])
    msg.body = f''' To reset your password, visit the following link: 
    {url_for('auth.reset_token', token=token, _external=True)}    
    
If you did not make this request please ignore this email and no changes will be made.
'''
    mail.send(msg,['kingwannyama01@gmail.com'])


@auth.route('/reset_password', methods=['POST', 'GET'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been send to reset your password.', category='info')
        return redirect(url_for('auth.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@auth.route('/reset_password/<token>', methods=['POST', 'GET'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Invalid or Expired token', category='warning')
        return redirect(url_for('auth.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        login_user(user)
        flash('Your password has been updated, You can now login!', category='success')
        return redirect(url_for('auth.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

website/views.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, abort
from flask_login import current_user, login_required

import main
from website.forms import UpdateAccountForm, PostForm
import secrets
from PIL import Image
import os

from website import db
from website.models import Post, User

views = Blueprint('views', __name__)


@views.route('/home')
@login_required
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', title='Home', posts=posts, user=current_user)


def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.split(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(main.app.root_path, 'static/profile_pics', picture_fn)

    # Resize images before upload
    output_size = (125, 125)
    i = Image.open(form_picture)
    i.thumbnail(output_size)
    i.save(picture_path)

    return picture_fn


@views.route('/account', methods=['POST', 'GET'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', category='success')
        return redirect(url_for('views.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', form=form, image_file=image_file)


@views.route('/')
def index():
    return render_template('index.html', title='Landing')


@views.route('/post/new', methods=['POST', 'GET'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created successfully!', category='success')
        return redirect(url_for('views.home'))
    return render_template('create_post.html', title='New post', form=form, legend='New Post')


@views.route('/int:post/<post_id>/update', methods=['POST', 'GET'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post was updated!', category='success')
        return redirect(url_for('views.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update_Post', post=post, form=form, legend='Update Post')


@views.route('/int:post/<post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=Post.title, post=post)


@views.route('/int:post/<post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post was deleted!', category='success')
    return redirect(url_for('views.home'))


@views.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@views.route('/about')
def about():
    return render_template('about.html', title='About')


@views.route('/contact')
def contact():
    return render_template('contact.html', title='Contacts')

website/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About us</h1>
{% endblock content %}

website/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section shadow p-3 mb-5 bg-body rounded">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Information</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group pt-3">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group pt-3">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

website/templates/contact.html
{% extends "layout.html" %}
{% block content %}
    <h1>Contact Us</h1>
{% endblock content %}

website/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
        <div class="content-section shadow p-3 mb-5 bg-body rounded">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-center">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group pt-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

website/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('views.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('views.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('views.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('views.home', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

website/templates/index.html
{% extends "layout.html" %}
{% block content %}
    <div class="card mb-3 mt-lg-5 shadow p-3 bg-body rounded">
          <div class="row g-0">
            <div class="col-md-6 shadow p-3 bg-body rounded">
              <img src="../static/images/lubra.png" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-6 shadow bg-body rounded">
              <div class="card-body bg-dark shadow p-3 rounded">
                <h5 class="card-title text-light">Welcome to Ball Kenya</h5>
                <p class="card-text text-light">Ball kenya is a blog app for all basketball players to share their views on the game across the country. We are trying to get to all corners of the country to have views and thoughts of players about the game.</p>
                <a href="{{ url_for('views.about') }}" class="btn btn-primary">About us</a>
              </div>
              <div class="card-body bg-dark shadow p-3 rounded">
                <h5 class="card-title text-light">Welcome to Ball Kenya</h5>
                <p class="card-text text-light">Ball kenya is a blog app for all basketball players to share their views on the game across the country. We are trying to get to all corners of the country to have views and thoughts of players about the game.</p>
                <a href="{{ url_for('views.contact') }}" class="btn btn-primary">Contact Us</a>
              </div>
              <div class="card-body bg-dark shadow p-3 rounded">
                <h5 class="card-title text-light">Welcome to Ball Kenya</h5>
                <p class="card-text text-light">Ball kenya is a blog app for all basketball players to share their views on the game across the country. We are trying to get to all corners of the country to have views and thoughts of players about the game.</p>
              </div>
            </div>
          </div>
    </div>
{% endblock content %}

website/templates/layout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% if title %}
        <title>Ball Kenya -{{ title }}</title>
    {% else %}
        <title>Ball Kenya</title>
    {% endif %}
</head>
<body>

    <header class="site-header mb-1 sticky-top">
        <nav class="navbar navbar-expand-lg bg-dark sticky-top">
          <div class="container-fluid">
            <a class="navbar-brand text-light" href="{{ url_for('views.index') }}"><img src="/static/images/logo.png" alt="Logo" width="90" height="70">Ball Kenya</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  {% if current_user.is_authenticated %}
                      <li class="nav-item">
                          <a class="nav-link "  href="{{ url_for('views.home') }}">Home</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('views.account') }}">Account</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('views.new_post') }}">Add Post</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                      </li>
                  {% else %}
                      <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('auth.register') }}" >Register</a>
                      </li>
                  {% endif %}
              </ul>
              <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </div>
        </nav>
    </header>
    <main role="main" class="container ">
      <div class="row">
        <div class="col-md-8 mt-lg-5 shadow p-3 mb-5 bg-steel rounded">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category , message in messages %}
                        {% if category == 'error' %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" aria-label="Close" data-bs-dismiss="alert"></button>
                            </div>
                        {% else %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" aria-label="Close" data-bs-dismiss="alert"></button>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4 mt-lg-5 shadow p-3 mb-5 bg-steel rounded">
          <div class="content-section">
           <legend>Standings.</legend>
            <p class='text-muted'>our future update section (at the moment it's just a decoration)
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">League Tables</li>
                <li class="list-group-item list-group-item-light">Results</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Schedules</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>


      <!-- ======= Footer ======= -->
  <footer id="footer" class="shadow p-3 bg-steel rounded">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 col-md-6 footer-info">
            <legend>Ball Kenya</legend>
            <p>
              Nairobi <br>
              50207, Kenya<br><br>
              <strong>Phone:</strong> +254 719787266 / +254 762141117<br>
              <strong>Email:</strong> lubanodennis@gmail.com<br>
            </p>
          </div>
            <div class="col-lg-4 footer-social">
                <legend>Social media</legend>
                <div class="social">
                    <a href="#"><i class="fa fa-facebook"></i> </a>
                    <a href="#"><i class="fa fa-twitter"></i> </a>
                    <a href="#"><i class="fa fa-snapchat-ghost"></i> </a>
                    <a href="#"><i class="fa fa-instagram"></i> </a>
                    <a href="#"><i class="fa fa-google-plus"></i> </a>
                </div>

            </div>
          <div class="col-lg-4 col-md-6 footer-newsletter">
            <legend>Our Newsletter</legend>
            <p>You can subscribe with us to get the latest and on time updates.</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Dennis Mabisi Lubano</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/bootstrap-3-one-page-template-free-shuffle/ -->
      </div>
    </div>
  </footer><!-- End Footer -->


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
</body>
</html>

website/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section shadow p-3 mb-5 bg-body rounded">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-center">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check pt-1">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group pt-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="{{ url_for('auth.reset_request') }}">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('auth.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

website/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('views.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('views.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('views.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

website/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section shadow p-3 mb-5 bg-body rounded">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-center">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group pt-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock %}

website/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section shadow p-3 mb-5 bg-body rounded">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" alt="">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('views.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('views.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
             {% if posts.page == page_num %}
                 <a class="btn btn-info mb-2 btn-sm" href="{{ url_for('views.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
             {% else %}
                 <a class="btn btn-outline-info mb-2 btn-sm" href="{{ url_for('views.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
             {% endif %}
        {% else %}
           ....
        {% endif %}
    {% endfor %}
{% endblock content %}